<a href="https://colab.research.google.com/github/RajeevRanjany/Applied-Machine-Learning/blob/main/BackWardPropagation_UsingKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]], columns= ['cgpa', 'profile_score','lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,5,12,7


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[ 0.16817558,  0.61779666],
        [-0.43570983, -0.54179996]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.2171787],
        [-1.3052738]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:

new_weights = [np.array([[0.1, 0.1],
[0.1, 0.1 ]], dtype = np.float32),
np.array([0., 0.], dtype=np.float32), np.array([[0.1],
[ 0.1]], dtype=np.float32), np.array([0.], dtype=np.float32)]

In [12]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error", optimizer=optimizer)

In [23]:
model.fit(df.iloc[:,[0,1]].values, df['lpa'].values, epochs=190,verbose = 1, batch_size=1)

Epoch 1/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1711
Epoch 2/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1688
Epoch 3/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1656
Epoch 4/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1644
Epoch 5/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1625
Epoch 6/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1619
Epoch 7/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1620
Epoch 8/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1566
Epoch 9/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1558
Epoch 10/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1547
Epoch 11/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1531
Epoch 12/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1488
Epoch 13/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1483
Epoch 14/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1447
Epoch 15/190
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1450
Epoch 16/190
3/3 ━━

In [24]:
model.get_weights()

[array([[0.26515228, 0.26515228],
        [0.45290813, 0.45290813]], dtype=float32),
 array([0.27739283, 0.27739283], dtype=float32),
 array([[0.40143612],
        [0.40143612]], dtype=float32),
 array([0.20670724], dtype=float32)]